### ISSUE TITLE
Cost issue when testing

### ISSUE THREAD

**Issue by sqlartist** [clemlesne/synthetic-rag-index#39]
Hi there, 

Can you explain if that final cost for indexing the document using this example on Azure is something a developer would have to pay or is there a developer aspect of Azure that allows developers to try out these types of examples safely without worry or concern that they may code something wrong and end up going bankrupt because of usage charges?

I genuinely love these examples and have followed Microsoft with a passion for 30 years and was a SQL MVP, (now Data MVP) and have used SQL Server since version 6.0 but am dismayed that single developer or consultants simply cannot do any sort of real world testing, including performance testing without paying a serious amount, sometimes unknown amounts to Azure platform.

I would really like to have run this code as its a research interest of mine.

regards

Trevor

**Comment by clemlesne** [comment]
Hello Trevor, I'm aware that Microsoft offers free credit for students, startups and sometimes for individuals. Additionally, the costs I'm describing in the doc is for a few thousands of pages. If you want to test, you can test with 3 pages PDFs :)

**Comment by sqlartist** [comment]
> Hello Trevor, I'm aware that Microsoft offers free credit for students, startups and sometimes for individuals. Additionally, the costs I'm describing in the doc is for a few thousands of pages. If you want to test, you can test with 3 pages PDFs :)

appreciate the reply Clemlesne. I know your project got the brunt of my disappointment with Azure :) I was so excited to see this though I may try and give it another go just for this.

thanks again

**Comment by clemlesne** [comment]
You are welcome to re-open if you have other related questions! :)
